Increase the timeout for rook-cluster
The ceph, and ceph-csi images are very large:

    $ minikube image ls --format=table -p dr1 | grep quay.io/ceph
    | quay.io/ceph/ceph          | v18       | sha256:a27483 | 447MB  |
    | quay.io/cephcsi/cephcsi    | v3.10.2   | sha256:10105e | 560MB  |

Watching pull image events during a build we see that these images were
pulled in 1m30s:

    $ kubectl events -A --context dr1 | awk '/pulled image/ {print $9, $11}' | grep ceph
    "rook/ceph:v1.13.7" 51.102s
    "quay.io/ceph/ceph:v18" 1m23.02s
    "quay.io/cephcsi/cephcsi:v3.10.2" 1m30.433s

Completion times for this build:

    $ grep -E 'rook-.+/start completed in' out/003.log
    2024-03-28 02:51:34,338 INFO    [dr1/0] addons/rook-operator/start completed in 59.02 seconds
    2024-03-28 02:51:36,423 INFO    [dr2/0] addons/rook-operator/start completed in 53.56 seconds
    2024-03-28 02:54:18,799 INFO    [dr1/0] addons/rook-cluster/start completed in 164.46 seconds
    2024-03-28 02:54:24,202 INFO    [dr2/0] addons/rook-cluster/start completed in 167.78 seconds
    2024-03-28 02:54:42,773 INFO    [dr2/0] addons/rook-pool/start completed in 18.57 seconds
    2024-03-28 02:54:45,949 INFO    [dr2/0] addons/rook-toolbox/start completed in 3.18 seconds
    2024-03-28 02:54:53,807 INFO    [dr1/0] addons/rook-pool/start completed in 35.01 seconds
    2024-03-28 02:54:56,929 INFO    [dr1/0] addons/rook-toolbox/start completed in 3.12 seconds

The rook-cluster addon is clearly much slower than others and with flaky
network like we have in the e2e lab, we may time out because of randomly
slow image pull.

Looking at rook-cluster completion time for 357 runs logs, we see that
the maximum value was very close to the current timeout:

    runs:   357
    avg:    140.58s
    max:    254.09s

We see random timeout in ceph-cluster, like:

    drenv.commands.Error: Command failed:
       command: ('addons/rook-cluster/start', 'dr2')
       exitcode: 1
       error:
          Traceback (most recent call last):
            ...
          drenv.commands.Error: Command failed:
             command: ('kubectl', 'wait', '--context', 'dr2',
                     'cephcluster/my-cluster',
                     '--for=jsonpath={.status.phase}=Ready',
                     '--namespace=rook-ceph', '--timeout=300s')
             exitcode: 1
             error:
                error: timed out waiting for the condition on cephclusters/my-cluster

Double the timeout for this wait.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>