CI: upgrade to setup-go v4 and disable cache with golangci
Below errors were seen with setup-go@v4 in golangci Lint:
Error: /usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/yaml_
test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/LICENSE:
Cannot open: File exists

Disabling Cache with golangci solves the problem and makes
sure that we are in a reecent setup-go as well.

Cache can be enabled once the resultant issue is fixed in
golangci lint action repo.
Issue that is to be tracked:
https://github.com/golangci/golangci-lint-action/issues/135

Updates: #1000
Signed-off-by: Shwetha K Acharya <sacharya@redhat.com>