Show more context when drenv.wait_for() times out
Show more context when the wait times out, since int this case we
don't show the kubectl command.

Example timeout:

    drenv.commands.Error: Command failed:
       command: ('addons/volsync/test', 'dr1', 'dr2')
       exitcode: 1
       error:
          Traceback (most recent call last):
            File "/home/nsoffer/src/ramen/test/addons/volsync/test", line 177, in <module>
              run_replication(cluster1)
            File "/home/nsoffer/src/ramen/test/addons/volsync/test", line 109, in run_replication
              drenv.wait_for(
            File "/home/nsoffer/src/ramen/test/drenv/__init__.py", line 52, in wait_for
              raise RuntimeError(
          RuntimeError: Timeout waiting for 'replicationsource/busybox-src'
          output='jsonpath={.status.lastManualSync}' namespace='busybox' profile='dr1' timeout=10

Signed-off-by: Nir Soffer <nsoffer@redhat.com>