e2e: Make TestReadConfig failures readable
When comparing expected objects use yaml format. This is makes it easier
to compare the objects and understand the failures.

Example failure:

    % go test -v ./config -run TestReadConfig
    === RUN   TestReadConfig
        config_test.go:59: expected
            channel:
              name: https-github-com-ramendr-ocm-ramen-samples-git
              namespace: e2e-gitops
            clusterSet: default
            clusters:
              c1:
                kubeconfig: dr1/config
              c2:
                kubeconfig: dr2/config
              hub:
                kubeconfig: hub/config
            deployers:
            - description: ApplicationSet deployer for ArgoCD
              name: appset
              type: appset
            - description: Subscription deployer for OCM subscriptions
              name: subscr
              type: subscr
            - description: Discovered Application deployer for discovered applications
              name: disapp
              type: disapp
            - description: Discovered Application deployer for discovered applications with recipe
              name: disapp-recipe
              type: disapp
            distro: ""
            drPolicy: dr-policy
            namespaces:
              argocdNamespace: ""
              ramenDRClusterNamespace: ""
              ramenHubNamespace: ""
              ramenOpsNamespace: ""
            pvcSpecs:
            - accessModes: ReadWriteOnce
              name: rbd
              storageClassName: rook-ceph-block
            - accessModes: ReadWriteMany
              name: cephfs
              storageClassName: rook-cephfs-fs1
            repo:
              branch: main
              url: https://github.com/RamenDR/ocm-ramen-samples.git
            tests:
            - deployer: appset
              pvcSpec: rbd
              workload: deploy
            - deployer: appset
              pvcSpec: cephfs
              workload: deploy

            got
            channel:
              name: https-github-com-ramendr-ocm-ramen-samples-git
              namespace: e2e-gitops
            clusterSet: default
            clusters:
              c1:
                kubeconfig: dr1/config
              c2:
                kubeconfig: dr2/config
              hub:
                kubeconfig: hub/config
            deployers:
            - description: ""
              name: appset
              type: appset
            - description: ""
              name: subscr
              type: subscr
            - description: ""
              name: disapp
              type: disapp
            distro: ""
            drPolicy: dr-policy
            namespaces:
              argocdNamespace: ""
              ramenDRClusterNamespace: ""
              ramenHubNamespace: ""
              ramenOpsNamespace: ""
            pvcSpecs:
            - accessModes: ReadWriteOnce
              name: rbd
              storageClassName: rook-ceph-block
            - accessModes: ReadWriteMany
              name: cephfs
              storageClassName: rook-cephfs-fs1
            repo:
              branch: main
              url: https://github.com/RamenDR/ocm-ramen-samples.git
            tests:
            - deployer: appset
              pvcSpec: rbd
              workload: deploy
            - deployer: appset
              pvcSpec: cephfs
              workload: deploy
    --- FAIL: TestReadConfig (0.00s)
    FAIL
    FAIL	github.com/ramendr/ramen/e2e/config	1.270s
    FAIL

So we have a failing tests - but the CI does not complain. The reason is
we don't run the unit tests in the CI. We need to find a good way to run
all tests except dr_test.go and validation_test.go,

Signed-off-by: Nir Soffer <nsoffer@redhat.com>