Fix example addon start hook
The start hook was not waiting for the deployment, which is a bad
example. Change the start and test hooks to be consistent with other
addons:
- in the start hook, wait until the deployment is rolled out
- in the test hook, run a test that require ready deployment

With this change, the random failures we see on github are gone -
instead we fail consistently (4 failures in 4 runs) with:

  drenv.commands.Error: Command failed:
     command: ('kubectl', 'exec', '--context', 'test-319c31e02513d53a5b0c2ebb71351f94-cluster',
               'deploy/example-deployment', '--', 'hostname')
     exitcode: 1
     error:
        error: unable to upgrade connection: container not found ("example")

When running on Fedora 37 and docker 20.10.23 this never fails.

Fixes: #997
Signed-off-by: Nir Soffer <nsoffer@redhat.com>