Fix waiting for volsync replication
We waited on `.status.lastManualSync` right after creating the
replication source, but there is a window where status or
status.lastManualSync are not reported, and the wait fails with:

    drenv.commands.Error: Command failed:
       command: ('kubectl', 'wait', '--context', 'dr1', 'replicationsource/busybox-src',
               '--for=jsonpath={.status.lastManualSync}=replication-1', '--namespace=busybox',
               '--timeout=120s')
       exitcode: 1
       error:
          error: status is not found

Strangely this wait is not needed on the system I tested on, maybe
this depends on kubectl version.

Now wait until `status.lastManualSync` is reported before wait on the
expected value.

Reported-by: Travis Janssen <tjanssen@redhat.com>
Signed-off-by: Nir Soffer <nsoffer@redhat.com>