Increase short addons timeouts
In some addons we use short timeouts (60 seconds). These timeouts always
work, when they are not, like:

    drenv.commands.Error: Command failed:
       command: ('addons/ocm-cluster/test', 'dr2', 'hub')
       exitcode: 1
       error:
          Traceback (most recent call last):
            File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/test", line 87, in <module>
              wait_for_deployment(cluster, hub)
            File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/test", line 40, in wait_for_deployment
              kubectl.wait(
            File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 90, in wait
              _watch("wait", *args, context=context, log=log)
            File "/home/nsoffer/src/ramen/test/drenv/kubectl.py", line 106, in _watch
              for line in commands.watch(*cmd, input=input):
            File "/home/nsoffer/src/ramen/test/drenv/commands.py", line 127, in watch
              raise Error(args, p.returncode, error)
          drenv.commands.Error: Command failed:
             command: ('kubectl', 'wait', '--context', 'dr2', 'deploy/example-deployment',
                 '--for=condition=available', '--timeout=60s')
             exitcode: 1
             error:
                error: timed out waiting for the condition on deployments/example-deployment

I think these timeouts starts to fail more now since we increased
concurrency when adding submariner addon, and the vms may be overloaded
during initial deployment.

Increase the 60 seconds timeouts to 120 seconds to avoid the random
failures.

We have some short timeouts in `test/basic-test/deploy`, but they never
failed, sine they don't run with overloaded clusters.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>