Log limactl errors
limactl logs everything to stderr, and we watch stderr to consume the
logs. Since we drop limactl logs when running in normal log level, when
limactl fail we don't have any info on the error, and the only way to
debug limactl error is run with verbose mode.

With this change we extract limactl log level and log errors as drenv
errors, so the last log before the error provide some info on the error.

Tested by uninstalling socket_vmnet:

    sudo make uninstall.launchd

With this limaclt fails to connect to the vmnet socket:

    % drenv start envs/vm.yaml
    2024-09-09 22:30:07,354 INFO    [vm] Starting environment
    2024-09-09 22:30:07,376 INFO    [cluster] Starting lima cluster
    2024-09-09 22:30:26,490 ERROR   [cluster] exiting, status={Running:false Degraded:false
        Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/nsoffer/.lima/cluster/ha.stderr.log")
    2024-09-09 22:30:26,492 ERROR   Command failed
    Traceback (most recent call last):
       ...
    drenv.commands.Error: Command failed:
       command: ('limactl', '--log-format=json', 'start', 'cluster')
       exitcode: 1
       error:

The lima error message is not very useful but this is what we have. This
should be improved in lima.

If we inspect the log file mentioned we can see the actual error:

    % tail -3 ~/.lima/cluster/ha.stderr.log
    {"level":"debug","msg":"Start tcp DNS listening on: 127.0.0.1:51618","time":"2024-09-09T22:30:26+03:00"}
    {"level":"info","msg":"new connection from  to ","time":"2024-09-09T22:30:26+03:00"}
    {"level":"fatal","msg":"dial unix /var/run/socket_vmnet: connect: connection refused","time":"2024-09-09T22:30:26+03:00"}

Signed-off-by: Nir Soffer <nsoffer@redhat.com>