Improve error environment
- Add duration argument for error addon for quicker testing.

- Replace example deployment with new sleep addon. The addon starts a
  sleep child process for testing termination of child processes.

- Add additional cluster to check that all addons on all clusters are
  terminated on errors.

- Add multiple workers and multiple addons to test that all workers in
  all clusters are canceled after an error.

- Add logging in the addons for easier debugging

Starting the environment stats this process tree:

    $ ps -f -o user,pid,ppid,pgid,args
    USER         PID    PPID    PGID COMMAND
    nsoffer   684655  684633  684655 bash
    nsoffer   900040  684655  900040  \_ drenv start envs/error.yaml -v
    nsoffer   900987  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   900993  900987  900040      |   \_ sleep 10.0
    nsoffer   900988  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   900992  900988  900040      |   \_ sleep 10.0
    nsoffer   900990  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   900994  900990  900040      |   \_ sleep 10.0
    nsoffer   900991  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   900995  900991  900040      |   \_ sleep 10.0
    nsoffer   901015  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   901019  901015  900040      |   \_ sleep 10.0
    nsoffer   901016  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   901020  901016  900040      |   \_ sleep 10.0
    nsoffer   901017  900040  900040      \_ python3 addons/error/start 10.0
    nsoffer   901018  900040  900040      \_ python3 addons/sleep/start 10.0
    nsoffer   901021  901018  900040          \_ sleep 10.0

Example run:

    $ drenv start envs/error.yaml -v
    2024-03-16 23:47:38,320 INFO    [error] Starting environment
    ...
    2024-03-16 23:48:25,171 ERROR   [c1/0] Cluster failed
    Traceback (most recent call last):
      ...
    drenv.commands.Error: Command failed:
       command: ('addons/error/start', '10.0')
       exitcode: 1
       error:
          Error addon failed

Since we did not terminate addons on errors, some addons and their child
process were orphaned after drenv terminated:

    $ ps -f -o user,pid,ppid,pgid,args
    USER         PID    PPID    PGID COMMAND
    nsoffer   684655  684633  684655 bash
    nsoffer   901053  682980  900040 python3 addons/sleep/start 60
    nsoffer   901054  901053  900040  \_ sleep 60
    nsoffer   901052  682980  900040 python3 addons/sleep/start 60
    nsoffer   901055  901052  900040  \_ sleep 60
    nsoffer   901051  682980  900040 python3 addons/sleep/start 60
    nsoffer   901056  901051  900040  \_ sleep 60
    nsoffer   901050  682980  900040 python3 addons/sleep/start 60
    nsoffer   901057  901050  900040  \_ sleep 60

In the CI the github runner terminate orphaned processes, but locally
they continue to run until they finish.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>