Retry creating mc alias
Before we create an alias, we ensure minio is up by doing a successful
HEAD request on minio health endpoint. However we still had 1 timeout in
200 runs:

2024-04-03 21:42:07,714 DEBUG   [dr1/2] Waiting until minio service is available
2024-04-03 21:42:07,899 DEBUG   [dr1/2] minio service is available in 0.01 seconds
2024-04-03 21:42:07,899 DEBUG   [dr1/2] Setting mc alias dr1
2024-04-03 21:42:08,209 ERROR   Command failed
Traceback (most recent call last):
  ...
drenv.commands.Error: Command failed:
   command: ('addons/minio/start', 'dr1')
   exitcode: 1
   error:
      Traceback (most recent call last):
        File "/home/nsoffer/ramen/test/addons/minio/start", line 59, in <module>
          wait(cluster)
        File "/home/nsoffer/ramen/test/addons/minio/start", line 40, in wait
          mc.set_alias(
        File "/home/nsoffer/ramen/test/drenv/mc.py", line 11, in set_alias
          commands.run("mc", "alias", "set", cluster, url, access_key, secret_key)
        File "/home/nsoffer/ramen/test/drenv/commands.py", line 91, in run
          raise Error(args, error, exitcode=p.returncode, output=output.decode())
      drenv.commands.Error: Command failed:
         command: ('mc', 'alias', 'set', 'dr1', 'http://192.168.122.200:30000', 'minio', 'minio123')
         exitcode: 1
         error:
            mc: <ERROR> Unable to initialize new alias from the provided credentials. Get
            "http://192.168.122.200:30000/probe-bsign-uhfgywjins9p99ll0dpi4btx3ecb3e/?location=":
            dial tcp 192.168.122.200:30000: connect: connection refused.

This smells like a bug in minio[1], maybe the health endpoints is
responding before the all endpoints, but since this is likely a
temporary issue, we don't want to fail the build.

[1] https://github.com/minio/minio/issues/19412

Signed-off-by: Nir Soffer <nsoffer@redhat.com>