Introduce commands.watch()
Add a helper to handle the common case in drenv; running a command and
logging its lines read from the child process stdout.

In the current code we redirect stderr to stdout, which makes it hard to
find the error message when a command fails. This helper avoids the
issue by reading both stdout and stderror at the same time. Text read
from stderr is buffered while the caller iterate over the lines read
from stdout.

Example usage:

    for line in commands.watch("minikube", "start"):
        logging.debug("%s", line)

If the command fails, an error is raised including the buffered error
text:

    commands.Error: Command failed:
       command: ("minikube", "start")
       exitcode: 1
       error:
          Error message from minikube

Part-of: #648
Signed-off-by: Nir Soffer <nsoffer@redhat.com>