Increase timeout in submariner test
In the test we deploy nginx and busybox - both are small images from
quay.io and complete very quickly locally, but in the e2e lab we have
flaky network and we see random timeouts like:

    drenv.commands.Error: Command failed:
       command: ('addons/submariner/test', 'hub', 'dr1', 'dr2')
       exitcode: 1
       error:
          Traceback (most recent call last):
            ...
          drenv.commands.Error: Command failed:
             command: ('kubectl', 'wait', '--context', 'dr1',
                     'deploy/nginx', '--for=condition=Available',
                     '--namespace=ns1', '--timeout=120s')
             exitcode: 1
             error:
                error: timed out waiting for the condition on deployments/nginx

We used 120 seconds which may be too low for something that depends on
the network, increasing to 300 seconds.

Fixes #1296

Signed-off-by: Nir Soffer <nsoffer@redhat.com>