Prefix names in ramen info
To dump kubeconfigs on clusters created with the --name-prefix option we
need to prefix the cluster names in the environment. The best place to
do this is in envfile.load() when we prefix all other names.

Without this fix, starting with --name-prefix cannot locate the clusters
in the kubeconfig:

    drenv.commands.Error: Command failed:
       command: ('kubectl', 'config', '--context', 'hub', 'view', '--flatten', '--minify')
       exitcode: 1
       error:
          error: cannot locate context hub

Signed-off-by: Nir Soffer <nsoffer@redhat.com>