Use last good commit for ocm-controller
Recent change[1] in `ocm-controller` broke the `work-manager` addon. The
addon is not installed on the managed clusters and we fail with:

    drenv.commands.Error: Command failed:
       command: ('addons/ocm-cluster/start', 'dr1', 'hub')
       exitcode: 1
       error:
          Traceback (most recent call last):
            File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 135, in <module>
              wait(cluster_name)
            File "/home/nsoffer/src/ramen/test/addons/ocm-cluster/start", line 59, in wait
              drenv.wait_for(deployment, namespace=ADDONS_NAMESPACE, profile=cluster)
            File "/home/nsoffer/src/ramen/test/drenv/__init__.py", line 50, in wait_for
              raise RuntimeError(f"Timeout waiting for {resource}")
          RuntimeError: Timeout waiting for deploy/klusterlet-addon-workmgr

On the hub we see:

    $ kubectl get managedclusteraddon -A --context hub | grep work-manager
    dr1         work-manager                  Unknown
    dr2         work-manager                  Unknown

Using the commit before this change fixes this issue.

To use the right commit, we pin the code using the commit hash and the
image tag for this commit hash. I don't know how to find the right image
tag, but quay.io can find the tag using the commit hash.

When the ocm-controller issue[2] is fixed we can move back to consume
main, or maybe keep updating the version manually until we get a proper
release tag.

[1] https://github.com/stolostron/multicloud-operators-foundation/commit/629b9e066e342d7c0ce8141aa2f1f3ca5128c771
[2] https://github.com/stolostron/multicloud-operators-foundation/issues/616

Signed-off-by: Nir Soffer <nsoffer@redhat.com>