Terminate child processes on error
Previously we terminated without any cleanup leaving orphaned child
processes around. Now we terminate all child processes (including child
processes created by child processes when terminating.

Shutting down cleanly in a multi-threaded multi-process application is
not easy.

- When staring the program, we ensure that drenv run as process group
  leader. This ensures that all child processes are part of the drenv
  process group. Child process started by child processes are also
  created in the same process group.

- When starting, we register SIGTERM handler. This ensures that when
  drenv is terminated, we use the same termination flow, terminating all
  child processes.

- When creating executor, we add them to a module executors list.  We
  abort the worker if shutdown has started.

- When running a hook, we abort the worker if shutdown has started.

- When the first addon fails, we shutdown the executor without waiting
  for running tasks, and cancel pending tasks. We don't log the error in
  the executor but let it propagate up to the new top level error
  handlers in main(), where we log all fatal errors.

- When handling an error in the top level error handler, we start
  shutdown, preventing any new child process to be created, and causing
  running tasks to abort. Then we shutdown all executors to cancel all
  pending tasks.

- Finally we terminate the entire process group using SIGHUP. This
  terminates any child process created before shutdown was started.

Example run using verbose logs to show the new debug logs:

    $ drenv start envs/error.yaml -v
    ...
    2024-03-17 02:34:58,639 DEBUG   [main] Add executor c1
    2024-03-17 02:34:58,639 INFO    [c1/0] Running addons/error/start
    2024-03-17 02:34:58,639 INFO    [c1/1] Running addons/sleep/start
    2024-03-17 02:34:58,640 INFO    [c1/2] Running addons/sleep/start
    2024-03-17 02:34:58,640 INFO    [c1/3] Running addons/sleep/start
    2024-03-17 02:34:58,711 DEBUG   [c1/0] Error addon will fail in 10.0 seconds
    2024-03-17 02:34:58,712 DEBUG   [c1/1] Sleep addon waiting 10.0 seconds
    2024-03-17 02:34:58,713 DEBUG   [c1/2] Sleep addon waiting 10.0 seconds
    2024-03-17 02:34:58,715 DEBUG   [c1/3] Sleep addon waiting 10.0 seconds
    2024-03-17 02:35:07,768 DEBUG   [c2/0] Sleep addon finished normally
    2024-03-17 02:35:07,768 DEBUG   [c2/1] Sleep addon finished normally
    2024-03-17 02:35:07,769 DEBUG   [c2/2] Sleep addon finished normally
    2024-03-17 02:35:07,772 DEBUG   [c2/3] Sleep addon finished normally
    2024-03-17 02:35:07,787 INFO    [c2/0] addons/sleep/start completed in 10.10 seconds
    2024-03-17 02:35:07,788 INFO    [c2/0] Running addons/sleep/start
    2024-03-17 02:35:07,790 INFO    [c2/1] addons/sleep/start completed in 10.10 seconds
    2024-03-17 02:35:07,790 INFO    [c2/1] Running addons/sleep/start
    2024-03-17 02:35:07,791 INFO    [c2/2] addons/sleep/start completed in 10.10 seconds
    2024-03-17 02:35:07,791 INFO    [c2/2] Running addons/sleep/start
    2024-03-17 02:35:07,794 INFO    [c2/3] addons/sleep/start completed in 10.10 seconds
    2024-03-17 02:35:07,794 INFO    [c2/3] Running addons/sleep/start
    2024-03-17 02:35:07,868 DEBUG   [c2/0] Sleep addon waiting 60 seconds
    2024-03-17 02:35:07,871 DEBUG   [c2/1] Sleep addon waiting 60 seconds
    2024-03-17 02:35:07,871 DEBUG   [c2/3] Sleep addon waiting 60 seconds
    2024-03-17 02:35:07,872 DEBUG   [c2/2] Sleep addon waiting 60 seconds
    2024-03-17 02:35:08,713 DEBUG   [c1/1] Sleep addon finished normally
    2024-03-17 02:35:08,714 DEBUG   [c1/2] Sleep addon finished normally
    2024-03-17 02:35:08,717 DEBUG   [c1/3] Sleep addon finished normally
    2024-03-17 02:35:08,734 INFO    [c1/2] addons/sleep/start completed in 10.09 seconds
    2024-03-17 02:35:08,734 INFO    [c1/2] Running addons/sleep/start
    2024-03-17 02:35:08,735 ERROR   Command failed
    Traceback (most recent call last):
      ...
    drenv.commands.Error: Command failed:
       command: ('addons/error/start', '10.0')
       exitcode: 1
       error:
          Error addon failed

    2024-03-17 02:35:08,736 DEBUG   [main] Starting shutdown
    2024-03-17 02:35:08,736 DEBUG   [main] Shutting down executor profiles
    2024-03-17 02:35:08,736 DEBUG   [main] Shutting down executor c2
    2024-03-17 02:35:08,737 DEBUG   [main] Shutting down executor c1
    2024-03-17 02:35:08,737 DEBUG   [main] Terminating process group 941645
    2024-03-17 02:35:08,737 INFO    [c1/3] addons/sleep/start completed in 10.10 seconds
    2024-03-17 02:35:08,737 DEBUG   [c1/3] Shutting down

The sleep addons and their child processes were terminated when drenv
terminated after the error.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>