drenv: Fix fragile test
kubectl 1.34.0 changes the delete message, breaking our test:

    >       assert out.strip() == f'pod "{name}" deleted'
    E       assert 'pod "example...ult namespace' == 'pod "example...x5hw" deleted'
    E
    E         - pod "example-deployment-68b69d9d56-vx5hw" deleted
    E         + pod "example-deployment-68b69d9d56-vx5hw" deleted from default namespace
    E         ?                                                  +++++++++++++++++++++++

Change the assert to check for the start of the string so it can work
with both old an new kubectl versions.

Signed-off-by: Nir Soffer <nsoffer@redhat.com>