Allow failure in stop script
With the current code, if a `stop` script fails, execution stops and the
entire command will fail. This prevents stopping the environment, which
is not helpful.

Change the code to allow failure for `stop` script. The error details
are logged, so the issue should be easy to debug, but the `stop` command
will stop the minikube profiles and succeed.

Example stop failure:

    $ drenv stop example.yaml
    2023-02-16 14:01:20,358 INFO    [example] Stopping environment
    2023-02-16 14:01:20,902 INFO    [ex1/0] Running example/stop
    2023-02-16 14:01:20,970 INFO    [ex2/0] Running example/stop
    2023-02-16 14:01:20,992 WARNING [ex1/0] example/stop failed: Command failed:
       command: ('example/stop', 'ex1')
       exitcode: 1
       error:
          Traceback (most recent call last):
            File "/home/nsoffer/src/ramen/test/example/stop", line 2, in <module>
              raise RuntimeError("Fake stop script error")
          RuntimeError: Fake stop script error

    2023-02-16 14:01:20,992 INFO    [ex1] Stopping cluster
    2023-02-16 14:01:21,055 WARNING [ex2/0] example/stop failed: Command failed:
       command: ('example/stop', 'ex2')
       exitcode: 1
       error:
          Traceback (most recent call last):
            File "/home/nsoffer/src/ramen/test/example/stop", line 2, in <module>
              raise RuntimeError("Fake stop script error")
          RuntimeError: Fake stop script error

    2023-02-16 14:01:21,055 INFO    [ex2] Stopping cluster
    2023-02-16 14:01:28,124 INFO    [ex1] Cluster stopped in 7.13 seconds
    2023-02-16 14:01:28,423 INFO    [ex2] Cluster stopped in 7.37 seconds
    2023-02-16 14:01:28,423 INFO    [example] Environment stopped in 8.06 seconds

Signed-off-by: Nir Soffer <nsoffer@redhat.com>